server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name swag.*;

    include /config/nginx/ssl.conf;
    include /config/nginx/proxy.conf;

    location / {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_app swag-mcp;
        set $upstream_port 8000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
