name: Dependencies & Security

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Dependency Review
      uses: actions/dependency-review-action@v4
      with:
        fail-on-severity: moderate
        allow-licenses: MIT, Apache-2.0, BSD-2-Clause, BSD-3-Clause, ISC

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Set up Python
      run: uv python install 3.12

    - name: Install dependencies
      run: uv sync

    - name: Run pip-audit
      run: |
        uv run pip-audit --format=json --output=audit-report.json || true
        uv run pip-audit --format=cyclonedx-json --output=audit-sbom.json || true

    - name: Upload audit results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: security-audit-results
        path: |
          audit-report.json
          audit-sbom.json

    - name: Run CodeQL analysis
      uses: github/codeql-action/init@v3
      with:
        languages: python

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Set up Python
      run: uv python install 3.12

    - name: Update dependencies
      run: |
        uv sync --upgrade
        uv lock --upgrade

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: update dependencies"
        title: "🔄 Weekly dependency updates"
        body: |
          ## Automated Dependency Updates

          This PR contains weekly dependency updates generated automatically.

          ### Changes
          - Updated dependencies to their latest compatible versions
          - Regenerated lock file

          ### Testing
          - [ ] All tests pass
          - [ ] No breaking changes detected
          - [ ] Security audit clean

          ---
          *This PR was created automatically by the dependency update workflow.*
        branch: automated/dependency-updates
        delete-branch: true
        draft: false
